// fly 截图 harness 的桩 preload：getStage/getPos 给真值，moveBy noop（只查窗内布局，不需要真移动窗口）
const { contextBridge } = require('electron');

const noop = () => {};
const pObj = (v) => () => Promise.resolve(v);

contextBridge.exposeInMainWorld('pet', {
  getStage: pObj({ minX: 0, maxX: 1200, minY: 0, floorY: 600 }),
  getPos: pObj([100, 500]),
  moveBy: noop,
  getCursor: pObj([600, 400]),
  activeWindow: pObj(null),
  inputContext: pObj({ typing: false, caret: null, active: null }),
  getSettings: pObj({}),
  getStats: pObj(null),
  getPowerState: pObj(false),
  getChatConfig: pObj({}),
  decideAction: pObj(null),
  findLedge: pObj(null),
  chatSend: pObj({}),
  chatProactive: pObj(null),
  chatInject: pObj({}),
  bubbleSay: noop,
  bubbleAnchor: noop,
  dragStart: noop,
  dragMove: noop,
  dragEnd: noop,
  driveStart: noop,
  fxStart: noop,
  folderDrop: noop,
  getPathForFile: (f) => (f && f.path) || '',
  logAppend: noop,
  mischiefStart: noop,
  openMenu: noop,
  openNotebook: noop,
  peekStart: noop,
  ropeEnd: noop,
  ropeMove: noop,
  ropeStart: noop,
  saveStats: noop,
  setActions: noop,
  setMouseIgnore: noop,
  swordStart: noop,
  throwPoop: noop,
  onArrowKey: noop,
  onBubbleDismissed: noop,
  onBubbleHidden: noop,
  onChatToken: () => noop,
  onDriveEnd: noop,
  onFeishuIncoming: noop,
  onFxExtDone: noop,
  onMenuAction: noop,
  onMischiefEnd: noop,
  onNotebookSay: noop,
  onPeekEnd: noop,
  onPowerState: noop,
  onSettings: noop,
  onSwordEnd: noop,
});
