const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('pet', {
  moveBy: (dx, dy) => ipcRenderer.send('move-by', dx, dy),
  dragStart: () => ipcRenderer.send('drag-start'),
  dragMove: () => ipcRenderer.send('drag-move'),
  dragEnd: () => ipcRenderer.send('drag-end'),
  openMenu: () => ipcRenderer.send('context-menu'),
  getPos: () => ipcRenderer.invoke('get-pos'),
  getStage: () => ipcRenderer.invoke('get-stage'),
  throwPoop: () => ipcRenderer.send('poop'),
  onPoop: (fn) => ipcRenderer.on('fx-poop', (_e, data) => fn(data)),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  setActions: (patch) => ipcRenderer.send('set-actions', patch),
  onSettings: (fn) => ipcRenderer.on('settings-changed', (_e, s) => fn(s)),
  getStats: () => ipcRenderer.invoke('get-stats'),
  saveStats: (s) => ipcRenderer.send('save-stats', s),
  logAppend: (entry) => ipcRenderer.send('log-append', entry),
  getLogs: () => ipcRenderer.invoke('get-logs'),
  clearLogs: () => ipcRenderer.send('clear-logs'),
  onLog: (fn) => ipcRenderer.on('log-new', (_e, entry) => fn(entry)),
  setMouseIgnore: (flag) => ipcRenderer.send('mouse-ignore', flag),
  swordStart: () => ipcRenderer.send('sword-start'),
  swordDone: () => ipcRenderer.send('sword-done'),
  onSword: (fn) => ipcRenderer.on('fx-sword', (_e, data) => fn(data)),
  onSwordEnd: (fn) => ipcRenderer.on('sword-end', () => fn()),
  driveStart: () => ipcRenderer.send('drive-start'),
  driveDone: () => ipcRenderer.send('drive-done'),
  onDrive: (fn) => ipcRenderer.on('fx-drive', (_e, data) => fn(data)),
  onDriveEnd: (fn) => ipcRenderer.on('drive-end', () => fn()),
  openNotebook: () => ipcRenderer.send('open-notebook'),
  notebookSay: (text) => ipcRenderer.send('notebook-say', text),
  onNotebookSay: (fn) => ipcRenderer.on('notebook-say', (_e, text) => fn(text)),
  findLedge: () => ipcRenderer.invoke('find-ledge'),
  ovIgnore: (flag) => ipcRenderer.send('ov-ignore', flag),
  mischiefStart: () => ipcRenderer.send('mischief-start'),
  mischiefDone: () => ipcRenderer.send('mischief-done'),
  onMischief: (fn) => ipcRenderer.on('fx-mischief', (_e, data) => fn(data)),
  onMischiefEnd: (fn) => ipcRenderer.on('mischief-end', () => fn()),
  onMenuAction: (fn) => ipcRenderer.on('menu-action', (_e, id) => fn(id)),
});
